version: '3.7'

services:
  database-checkout:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: checkout
      TZ: America/Sao_Paulo
      PGTZ: America/Sao_Paulo
    container_name: db-checkout
    ports:
      - 5432:5432
    volumes:
      - /docker-volumes/postgresql/db-checkout:/var/lib/postgresql/data
  database-payment:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: payment
      TZ: America/Sao_Paulo
      PGTZ: America/Sao_Paulo
    container_name: db-payment
    ports:
      - 5433:5432
    volumes:
      - /docker-volumes/postgresql/db-payment:/var/lib/postgresql/data